version: '1'
services:
  app:
    build: ./app
    depends_on:
      - api
    ports:
      - "3000:3000"
    volumes:
      - ./app:/usr/src/app/
      - /usr/src/app/node_modules

  api:
    build: ./api
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - ./api:/usr/src/api/
      - /usr/src/api/node_modules

  postgres:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=freddie
      - POSTGRES_PASSWORD=freddielovescake
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./api/scripts/seed.sql:/docker-entrypoint-initdb.d/seed.sql