version: "1"
services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile.yml
    restart: always
    env_file: ./docker.db.env
    ports:
      - "5432:5432"
  flyway:
    build:
      context: ./db
      dockerfile: Dockerfile.flyway.yml
    command: -locations="filesystem:/schema" -connectRetries=3 info migrate
    env_file: ./docker.db.env
    depends_on:
      - db
  populate:
    build:
      context: ./db
      dockerfile: Dockerfile.populate.yml
    env_file: ./docker.db.env
    restart: on-failure
    depends_on:
      - db
  app:
    build: ./app
    depends_on:
      - api
    ports:
      - "3000:3000"
    volumes:
      - ./app:/usr/src/app/
      - /usr/src/app/node_modules
  api:
    build: ./api
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./api:/usr/src/api/
      - /usr/src/api/node_modules
